image:
  file: .gitpod.Dockerfile
# image: codesimple/elm

tasks:
  - init: 'elm install'
    command: 'elm reactor --port=3000'

vscode:
  extensions:
    - elmtooling.elm-ls-vscode@2.0.3:A/c/4djwO7BtcqUqFbi0iw==